import {
  Wifi,
  Car,
  UtensilsCrossed,
  Snowflake,
  Flame,
  Waves,
  Umbrella,
  Coffee,
  Tv,
  WashingMachine,
  Trees,
  ShowerHead,
  Bath,
  GalleryVertical,
  Baby,
  Sailboat,
  Mountain,
  type LucideIcon,
} from "lucide-react";
import type { Amenity } from "@/types/property";

export const AMENITY_ICONS: Record<Amenity, LucideIcon> = {
  wifi: Wifi,
  parking: Car,
  kitchen: UtensilsCrossed,
  ac: Snowflake,
  bbq: Flame,
  pool: Waves,
  beach: Umbrella,
  breakfast: Coffee,
  tv: Tv,
  washer: WashingMachine,
  terrace: Trees,
  shower: ShowerHead,
  bath: Bath,
  balcony: GalleryVertical,
  playground: Baby,
  lake_view: Sailboat,
  mountain_view: Mountain,
};
